"""add role to group_members

Revision ID: 2dd6a9b9521a
Revises: 5b88de1fae6d
Create Date: 2026-02-28 10:05:11.146568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd6a9b9521a'
down_revision: Union[str, Sequence[str], None] = '5b88de1fae6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    memberrole = sa.Enum('owner', 'admin', 'member', name='memberrole')
    memberrole.create(op.get_bind())
    op.add_column('group_members', sa.Column('role', memberrole, server_default='member', nullable=False))
    # ### end Alembic commands ###

    # Set existing group owners to owner role
    op.execute(
        """
        UPDATE group_members gm
        SET role = 'owner'
        FROM groups g
        WHERE gm.group_id = g.id AND gm.user_id = g.owner_id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'role')
    op.execute("DROP TYPE IF EXISTS memberrole")
    # ### end Alembic commands ###
