"""add join_policy and invite_token to groups

Revision ID: 55ad97905190
Revises: e96f3bd1a8c8
Create Date: 2026-02-28 09:17:40.394971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ad97905190'
down_revision: Union[str, Sequence[str], None] = 'e96f3bd1a8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


joinpolicy_enum = sa.Enum('public', 'private', name='joinpolicy')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    joinpolicy_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('groups', sa.Column('join_policy', joinpolicy_enum, server_default='public', nullable=False))
    op.add_column('groups', sa.Column('invite_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_groups_invite_token'), 'groups', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_invite_token'), table_name='groups')
    op.drop_column('groups', 'invite_token')
    op.drop_column('groups', 'join_policy')
    joinpolicy_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
