"""add_contests_and_game_record_contest_id

Revision ID: efffe4263d09
Revises: 292be66d16b0
Create Date: 2026-03-01 07:56:04.482920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efffe4263d09'
down_revision: Union[str, Sequence[str], None] = '292be66d16b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('ranking_type', sa.Enum('score', 'match_point', name='rankingtype'), server_default='score', nullable=False),
    sa.Column('uma_1st', sa.Integer(), server_default='30', nullable=False),
    sa.Column('uma_2nd', sa.Integer(), server_default='10', nullable=False),
    sa.Column('uma_3rd', sa.Integer(), server_default='-10', nullable=False),
    sa.Column('uma_4th', sa.Integer(), server_default='-30', nullable=False),
    sa.Column('scoring_1st', sa.Integer(), server_default='4', nullable=False),
    sa.Column('scoring_2nd', sa.Integer(), server_default='2', nullable=False),
    sa.Column('scoring_3rd', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scoring_4th', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_created_by_id'), 'contests', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_contests_group_id'), 'contests', ['group_id'], unique=False)
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.add_column('game_records', sa.Column('contest_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_game_records_contest_id'), 'game_records', ['contest_id'], unique=False)
    op.create_foreign_key(None, 'game_records', 'contests', ['contest_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_records', type_='foreignkey')
    op.drop_index(op.f('ix_game_records_contest_id'), table_name='game_records')
    op.drop_column('game_records', 'contest_id')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_group_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_created_by_id'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
