USERNAME_MAX_LENGTH = 50
USERNAME_PATTERN = r"^[a-zA-Z0-9가-힣_-]+$"
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 100
NICKNAME_MAX_LENGTH = 50
GROUP_NAME_MAX_LENGTH = 100
GROUP_DESCRIPTION_MAX_LENGTH = 500
EVENT_NAME_MAX_LENGTH = 100
