"""add game_records

Revision ID: 0135acc74e41
Revises: 2dd6a9b9521a
Create Date: 2026-02-28 19:07:44.489059

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0135acc74e41'
down_revision: str | Sequence[str] | None = '2dd6a9b9521a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('east_player_id', sa.Integer(), nullable=False),
    sa.Column('south_player_id', sa.Integer(), nullable=False),
    sa.Column('west_player_id', sa.Integer(), nullable=False),
    sa.Column('north_player_id', sa.Integer(), nullable=False),
    sa.Column('east_point', sa.Integer(), nullable=False),
    sa.Column('south_point', sa.Integer(), nullable=False),
    sa.Column('west_point', sa.Integer(), nullable=False),
    sa.Column('north_point', sa.Integer(), nullable=False),
    sa.Column('game_link', sa.String(length=500), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['east_player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['north_player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['south_player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['west_player_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_records_east_player_id'), 'game_records', ['east_player_id'], unique=False)
    op.create_index(op.f('ix_game_records_group_id'), 'game_records', ['group_id'], unique=False)
    op.create_index(op.f('ix_game_records_id'), 'game_records', ['id'], unique=False)
    op.create_index(op.f('ix_game_records_north_player_id'), 'game_records', ['north_player_id'], unique=False)
    op.create_index(op.f('ix_game_records_south_player_id'), 'game_records', ['south_player_id'], unique=False)
    op.create_index(op.f('ix_game_records_west_player_id'), 'game_records', ['west_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_records_west_player_id'), table_name='game_records')
    op.drop_index(op.f('ix_game_records_south_player_id'), table_name='game_records')
    op.drop_index(op.f('ix_game_records_north_player_id'), table_name='game_records')
    op.drop_index(op.f('ix_game_records_id'), table_name='game_records')
    op.drop_index(op.f('ix_game_records_group_id'), table_name='game_records')
    op.drop_index(op.f('ix_game_records_east_player_id'), table_name='game_records')
    op.drop_table('game_records')
    # ### end Alembic commands ###
