"""add invite_token_expires_at to groups

Revision ID: 117f2721bb07
Revises: 55ad97905190
Create Date: 2026-02-28 09:22:25.933960

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '117f2721bb07'
down_revision: str | Sequence[str] | None = '55ad97905190'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('invite_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'invite_token_expires_at')
    # ### end Alembic commands ###
