"""add uma fields to groups

Revision ID: 292be66d16b0
Revises: 42da90c5798e
Create Date: 2026-03-01 07:07:30.926072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '292be66d16b0'
down_revision: str | Sequence[str] | None = '42da90c5798e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('uma_1st', sa.Integer(), server_default='30', nullable=False))
    op.add_column('groups', sa.Column('uma_2nd', sa.Integer(), server_default='10', nullable=False))
    op.add_column('groups', sa.Column('uma_3rd', sa.Integer(), server_default='-10', nullable=False))
    op.add_column('groups', sa.Column('uma_4th', sa.Integer(), server_default='-30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'uma_4th')
    op.drop_column('groups', 'uma_3rd')
    op.drop_column('groups', 'uma_2nd')
    op.drop_column('groups', 'uma_1st')
    # ### end Alembic commands ###
