"""add created_by_id to game_records

Revision ID: 42da90c5798e
Revises: 0135acc74e41
Create Date: 2026-02-28 19:12:39.280799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42da90c5798e'
down_revision: Union[str, Sequence[str], None] = '0135acc74e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_records', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_game_records_created_by_id'), 'game_records', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'game_records', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_records', type_='foreignkey')
    op.drop_index(op.f('ix_game_records_created_by_id'), table_name='game_records')
    op.drop_column('game_records', 'created_by_id')
    # ### end Alembic commands ###
