"""add_group_default_event_settings

Revision ID: e975d38d6630
Revises: bab066adfb89
Create Date: 2026-03-03 10:41:49.588215

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e975d38d6630'
down_revision: str | Sequence[str] | None = 'bab066adfb89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('default_ranking_type', sa.Enum('score', 'match_point', name='rankingtype'), server_default='score', nullable=False))
    op.add_column('groups', sa.Column('default_uma_1st', sa.Integer(), server_default='30', nullable=False))
    op.add_column('groups', sa.Column('default_uma_2nd', sa.Integer(), server_default='10', nullable=False))
    op.add_column('groups', sa.Column('default_uma_3rd', sa.Integer(), server_default='-10', nullable=False))
    op.add_column('groups', sa.Column('default_uma_4th', sa.Integer(), server_default='-30', nullable=False))
    op.add_column('groups', sa.Column('default_scoring_1st', sa.Integer(), server_default='4', nullable=False))
    op.add_column('groups', sa.Column('default_scoring_2nd', sa.Integer(), server_default='2', nullable=False))
    op.add_column('groups', sa.Column('default_scoring_3rd', sa.Integer(), server_default='1', nullable=False))
    op.add_column('groups', sa.Column('default_scoring_4th', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'default_scoring_4th')
    op.drop_column('groups', 'default_scoring_3rd')
    op.drop_column('groups', 'default_scoring_2nd')
    op.drop_column('groups', 'default_scoring_1st')
    op.drop_column('groups', 'default_uma_4th')
    op.drop_column('groups', 'default_uma_3rd')
    op.drop_column('groups', 'default_uma_2nd')
    op.drop_column('groups', 'default_uma_1st')
    op.drop_column('groups', 'default_ranking_type')
    # ### end Alembic commands ###
